runtime: python311

#This is the default entrypoint.
entrypoint: gunicorn -b :$PORT erichsblog.wsgi

handlers:
  - url: /static/
    static_dir: static/ 
  
  - url: /media/
    static_dir: media/

  - url: /.*  # This catches all other requests
    secure: always
    redirect_http_response_code: 301
    script: auto
